-- =============================================================================
-- KCCA Internship Management System — Seed Data
-- =============================================================================
--
-- NOTE: This file cannot contain real bcrypt password hashes because bcrypt
-- hashing requires a runtime (Node.js).  Passwords are seeded programmatically
-- by the backend when the server starts for the first time:
--
--   npm start  →  initializeDatabase()  →  seedDemoUsers()
--
-- All demo users are created with the password:  password123
--
-- Demo login credentials:
--   applicant@kcca.go.ug  /  password123  (role: applicant)
--   hr@kcca.go.ug         /  password123  (role: hr)
--   admin@kcca.go.ug      /  password123  (role: admin)
--
-- To apply this seed manually (after the server has run once and hashed the
-- passwords), you can re-run:
--
--   node -e "require('./src/config/database').seedDemoUsers().then(() => process.exit())"
--
-- from the backend/ directory.
-- =============================================================================

-- The actual INSERT statements are executed by seedDemoUsers() in
-- backend/src/config/database.js using ON CONFLICT DO NOTHING so they are
-- idempotent and safe to run multiple times.
