// src/api/mockData.js
import { KCCA_DEPARTMENTS } from "../utils/constants";

export const MOCK_USERS = {
  "applicant@kcca.go.ug": {
    id: "U001", name: "Sarah Nakimuli", email: "applicant@kcca.go.ug",
    password: "password123", role: "applicant", phone: "+256 701 234 567",
    gender: "Female", dob: "2001-03-14", district: "Kampala", nationality: "Ugandan",
    address: "Ntinda, Kampala", university: "Makerere University",
    course: "Computer Science", yearOfStudy: "3rd Year", gpa: "4.2",
    studentId: "16/U/0001/PS", graduationYear: "2026",
    skills: ["JavaScript", "Python", "React", "Data Analysis"],
    languages: ["English", "Luganda"],
    emergencyContact: { name: "John Nakimuli", relationship: "Father", phone: "+256 702 111 222" },
    references: [
      { name: "Prof. David Musoke", institution: "Makerere University", email: "d.musoke@mak.ac.ug", phone: "+256 772 100 200" },
    ],
    avatar: null, status: "active", joinedAt: "2026-07-01T00:00:00Z",
    emailVerified: true, notifyEmail: true, notifySMS: true, notifyPortal: true,
  },
  "hr@kcca.go.ug": {
    id: "U002", name: "James Ssemakula", email: "hr@kcca.go.ug",
    password: "password123", role: "hr", department: "Human Resources",
    title: "HR Officer", phone: "+256 703 456 789", status: "active",
    avatar: null, joinedAt: "2025-01-15T00:00:00Z",
  },
  "admin@kcca.go.ug": {
    id: "U003", name: "Patricia Nakato", email: "admin@kcca.go.ug",
    password: "password123", role: "admin", title: "System Administrator",
    phone: "+256 704 789 012", status: "active", avatar: null,
    joinedAt: "2024-06-01T00:00:00Z",
  },
};

export const MOCK_INTERNSHIPS = [
  { id: "INT001", title: "Software Development Intern", department: "ICT",
    description: "Work with the ICT team to develop and maintain internal systems used across KCCA divisions. You will be involved in both front-end and back-end development, database management, and system testing.", 
    requirements: ["Computer Science or IT degree", "2nd year and above", "Basic knowledge of web technologies", "Problem-solving skills"],
    qualifications: "Bachelor's Degree", vacancies: 4, deadline: "2026-08-15", supervisor: "Mr. Peter Mwesigwa",
    duration: "3 Months", location: "City Hall – Kampala", status: "open", posted: "2026-07-01", applicants: 23 },
  { id: "INT002", title: "Public Health Intern", department: "Public Health Services",
    description: "Assist in community health outreach programs, data collection, and health service delivery across Kampala divisions.",
    requirements: ["Public Health / Medicine / Nursing", "3rd year and above", "Good communication skills", "Field work capability"],
    qualifications: "Bachelor's Degree", vacancies: 6, deadline: "2026-08-20", supervisor: "Dr. Aisha Namazzi",
    duration: "6 Months", location: "Kawempe Division", status: "open", posted: "2026-07-05", applicants: 41 },
  { id: "INT003", title: "Urban Planning Intern", department: "Urban Planning",
    description: "Support urban planning professionals in land-use mapping, environmental impact assessments, and city development projects.",
    requirements: ["Urban Planning / Architecture / Civil Engineering", "AutoCAD proficiency", "GIS knowledge preferred"],
    qualifications: "Bachelor's Degree", vacancies: 3, deadline: "2026-08-30", supervisor: "Eng. Moses Kabugo",
    duration: "4 Months", location: "City Hall – Kampala", status: "open", posted: "2026-07-08", applicants: 15 },
  { id: "INT004", title: "Finance & Accounts Intern", department: "Finance & Planning",
    description: "Assist in financial reporting, budget preparation, accounts reconciliation, and supporting audit processes.",
    requirements: ["Finance / Accounting / Commerce", "ACCA or CPA Part I", "Excel proficiency", "Attention to detail"],
    qualifications: "Bachelor's Degree", vacancies: 5, deadline: "2026-09-01", supervisor: "Ms. Grace Akullo",
    duration: "3 Months", location: "City Hall – Kampala", status: "open", posted: "2026-07-10", applicants: 37 },
  { id: "INT005", title: "Legal Research Intern", department: "Legal Services",
    description: "Conduct legal research, assist with drafting documents, and support case management and compliance activities.",
    requirements: ["LLB – 3rd year +", "Research & writing skills", "Knowledge of Ugandan law"],
    qualifications: "Bachelor's Degree", vacancies: 2, deadline: "2026-08-10", supervisor: "Adv. Ruth Namukasa",
    duration: "2 Months", location: "City Hall – Kampala", status: "open", posted: "2026-07-12", applicants: 18 },
  { id: "INT006", title: "Environmental Management Intern", department: "Environment",
    description: "Support environmental monitoring, waste management, and climate resilience projects across Kampala.",
    requirements: ["Environmental Science / Natural Resources", "Field work capability", "Report writing"],
    qualifications: "Bachelor's Degree", vacancies: 3, deadline: "2026-08-25", supervisor: "Dr. Charles Byaruhanga",
    duration: "3 Months", location: "Makindye Division", status: "open", posted: "2026-07-15", applicants: 12 },
  { id: "INT007", title: "Education Program Intern", department: "Education",
    description: "Assist in implementing school programs, learner outcome data collection, and supporting education officers.",
    requirements: ["Education / Social Sciences", "Data and report skills", "Passion for community development"],
    qualifications: "Bachelor's Degree", vacancies: 8, deadline: "2026-09-10", supervisor: "Ms. Judith Nakintu",
    duration: "6 Months", location: "Rubaga Division", status: "open", posted: "2026-07-18", applicants: 54 },
  { id: "INT008", title: "Civil Engineering Intern", department: "Engineering & Technical Services",
    description: "Support road construction supervision, building inspections, and infrastructure maintenance projects.",
    requirements: ["Civil Engineering – 3rd year +", "AutoCAD / Civil 3D", "Safety awareness"],
    qualifications: "Bachelor's Degree", vacancies: 4, deadline: "2026-08-18", supervisor: "Eng. David Opolot",
    duration: "4 Months", location: "Nakawa Division", status: "open", posted: "2026-07-20", applicants: 29 },
  { id: "INT009", title: "HR & Administration Intern", department: "Human Resources",
    description: "Support recruitment processes, employee records management, and HR administrative tasks.",
    requirements: ["HRM / Business Admin", "Organizational skills", "Confidentiality"],
    qualifications: "Bachelor's Degree", vacancies: 2, deadline: "2026-08-05", supervisor: "Ms. Patricia Nakato",
    duration: "3 Months", location: "City Hall – Kampala", status: "open", posted: "2026-07-22", applicants: 31 },
  { id: "INT010", title: "Community Development Intern", department: "Gender & Community Services",
    description: "Assist with gender-responsive programs, youth empowerment, and community engagement activities.",
    requirements: ["Social Work / Gender Studies", "Community engagement", "Luganda a plus"],
    qualifications: "Bachelor's Degree", vacancies: 5, deadline: "2026-09-05", supervisor: "Ms. Fatuma Namuganza",
    duration: "6 Months", location: "Central Division", status: "open", posted: "2026-07-25", applicants: 47 },
];

export const MOCK_APPLICATIONS = [
  { id: "APP001", internshipId: "INT001", internshipTitle: "Software Development Intern",
    department: "ICT", applicantId: "U001", applicantName: "Sarah Nakimuli",
    university: "Makerere University", course: "Computer Science", gender: "Female", gpa: "4.2",
    status: "shortlisted", submittedAt: "2026-07-10T09:30:00Z",
    reviewNote: "Strong academic record. Shortlisted for interview.",
    timeline: [
      { status: "submitted",    date: "2026-07-10T09:30:00Z", note: "Application submitted successfully." },
      { status: "under_review", date: "2026-07-12T11:00:00Z", note: "Application is under review by the HR team." },
      { status: "shortlisted",  date: "2026-07-18T09:00:00Z", note: "Congratulations! You have been shortlisted." },
    ]},
  { id: "APP002", internshipId: "INT004", internshipTitle: "Finance & Accounts Intern",
    department: "Finance & Planning", applicantId: "U001", applicantName: "Sarah Nakimuli",
    university: "Makerere University", course: "Computer Science", gender: "Female", gpa: "4.2",
    status: "under_review", submittedAt: "2026-07-15T11:00:00Z", reviewNote: "",
    timeline: [
      { status: "submitted",    date: "2026-07-15T11:00:00Z", note: "Application submitted successfully." },
      { status: "under_review", date: "2026-07-17T08:00:00Z", note: "Application is under review." },
    ]},
  { id: "APP003", internshipId: "INT007", internshipTitle: "Education Program Intern",
    department: "Education", applicantId: "U004", applicantName: "Allan Mugisha",
    university: "Uganda Christian University", course: "Education", gender: "Male", gpa: "3.8",
    status: "accepted", submittedAt: "2026-07-05T08:00:00Z",
    timeline: [
      { status: "submitted",    date: "2026-07-05T08:00:00Z", note: "Application submitted." },
      { status: "under_review", date: "2026-07-08T09:00:00Z", note: "Under review." },
      { status: "shortlisted",  date: "2026-07-14T10:00:00Z", note: "Shortlisted." },
      { status: "interview",    date: "2026-07-20T10:00:00Z", note: "Interview scheduled." },
      { status: "accepted",     date: "2026-07-25T14:00:00Z", note: "Offer issued. Welcome to KCCA!" },
    ]},
  { id: "APP004", internshipId: "INT002", internshipTitle: "Public Health Intern",
    department: "Public Health Services", applicantId: "U005", applicantName: "Brenda Atim",
    university: "MUST", course: "Public Health", gender: "Female", gpa: "3.1",
    status: "rejected", submittedAt: "2026-07-08T10:00:00Z",
    reviewNote: "Qualifications do not meet minimum requirements.",
    timeline: [
      { status: "submitted",    date: "2026-07-08T10:00:00Z", note: "Application submitted." },
      { status: "under_review", date: "2026-07-10T09:00:00Z", note: "Under review." },
      { status: "rejected",     date: "2026-07-16T11:00:00Z", note: "Application not successful at this time." },
    ]},
  { id: "APP005", internshipId: "INT003", internshipTitle: "Urban Planning Intern",
    department: "Urban Planning", applicantId: "U006", applicantName: "Emmanuel Kizza",
    university: "Kyambogo University", course: "Architecture", gender: "Male", gpa: "3.9",
    status: "interview", submittedAt: "2026-07-12T14:00:00Z",
    timeline: [
      { status: "submitted",    date: "2026-07-12T14:00:00Z", note: "Application submitted." },
      { status: "under_review", date: "2026-07-14T09:00:00Z", note: "Under review." },
      { status: "shortlisted",  date: "2026-07-20T10:00:00Z", note: "Shortlisted." },
      { status: "interview",    date: "2026-07-26T11:00:00Z", note: "Interview scheduled for 2026-08-02." },
    ]},
  { id: "APP006", internshipId: "INT001", internshipTitle: "Software Development Intern",
    department: "ICT", applicantId: "U007", applicantName: "Grace Namukasa",
    university: "Makerere University Business School", course: "Information Technology", gender: "Female", gpa: "4.0",
    status: "submitted", submittedAt: "2026-07-20T13:00:00Z",
    timeline: [{ status: "submitted", date: "2026-07-20T13:00:00Z", note: "Application submitted." }]},
];

export const MOCK_INTERVIEWS = [
  { id: "IVW001", applicationId: "APP001", applicantName: "Sarah Nakimuli",
    internshipTitle: "Software Development Intern", department: "ICT",
    date: "2026-08-05", time: "10:00 AM",
    venue: "KCCA Boardroom 2, City Hall, 3rd Floor",
    panelMembers: ["Mr. Peter Mwesigwa (ICT Director)", "Ms. Rose Nabwire (HR Manager)", "Mr. David Okello (ICT Lead)"],
    instructions: "Please bring your original academic documents, a copy of your CV, and your National ID. Arrive 15 minutes before the scheduled time. Smart casual dress code.",
    meetingLink: "https://meet.google.com/kcca-int-2026", mode: "physical", status: "scheduled", response: null },
];

export const MOCK_NOTIFICATIONS = [
  { id: "N001", title: "Application Shortlisted", type: "success", read: false, createdAt: "2026-07-18T09:00:00Z",
    message: "Your application for Software Development Intern has been shortlisted. Check your interview schedule." },
  { id: "N002", title: "Interview Scheduled", type: "info", read: false, createdAt: "2026-07-20T10:00:00Z",
    message: "Your interview for Software Development Intern is scheduled on 5th August 2026 at 10:00 AM at City Hall." },
  { id: "N003", title: "Application Received", type: "info", read: true, createdAt: "2026-07-15T11:30:00Z",
    message: "We have received your application for Finance & Accounts Intern. You will be notified of updates." },
  { id: "N004", title: "New Internship Posted", type: "info", read: true, createdAt: "2026-07-25T08:00:00Z",
    message: "KCCA has posted a new internship: Community Development Intern. Apply before 5th September 2026." },
  { id: "N005", title: "Deadline Reminder", type: "warning", read: true, createdAt: "2026-07-26T08:00:00Z",
    message: "Reminder: The deadline for HR & Administration Intern is in 10 days (5th August 2026)." },
];

export const MOCK_USERS_LIST = [
  { id: "U001", name: "Sarah Nakimuli",    email: "applicant@kcca.go.ug", role: "applicant",  status: "active",   joinedAt: "2026-07-01" },
  { id: "U002", name: "James Ssemakula",  email: "hr@kcca.go.ug",        role: "hr",         status: "active",   joinedAt: "2025-01-15" },
  { id: "U003", name: "Patricia Nakato",  email: "admin@kcca.go.ug",     role: "admin",      status: "active",   joinedAt: "2024-06-01" },
  { id: "U004", name: "Allan Mugisha",    email: "allan.m@kcca.go.ug",   role: "applicant",  status: "active",   joinedAt: "2026-07-05" },
  { id: "U005", name: "Brenda Atim",      email: "brenda.a@kcca.go.ug",  role: "applicant",  status: "inactive", joinedAt: "2026-07-08" },
  { id: "U006", name: "Emmanuel Kizza",   email: "emma.k@kcca.go.ug",    role: "applicant",  status: "active",   joinedAt: "2026-07-12" },
  { id: "U007", name: "Florence Nalwoga", email: "florence.n@kcca.go.ug",role: "supervisor", status: "active",   joinedAt: "2025-03-01" },
  { id: "U008", name: "Grace Namukasa",   email: "grace.n@kcca.go.ug",   role: "applicant",  status: "active",   joinedAt: "2026-07-20" },
];

export const MOCK_DEPARTMENTS = KCCA_DEPARTMENTS.map((name, i) => ({
  id: `DEPT${String(i+1).padStart(3,"0")}`, name,
  head: ["Eng. David Opolot","Dr. Aisha Namazzi","Ms. Judith Nakintu","Ms. Grace Akullo","Adv. Ruth Namukasa","Eng. Moses Kabugo","Ms. Fatuma Namuganza","Mr. Peter Mwesigwa","Mr. Isaac Ogen","Ms. Patricia Nakato","Dr. Charles Byaruhanga","Mr. Samuel Muwonge"][i],
  openings: [4,6,8,5,2,3,5,4,2,8,3,2][i],
  totalInterns: [12,28,34,18,7,9,21,15,6,31,10,4][i],
  status: "active",
}));

export const MOCK_AUDIT_LOGS = [
  { id: "L001", action: "LOGIN",            user: "admin@kcca.go.ug",     detail: "Admin logged in",                         timestamp: "2026-07-27T08:00:00Z", ip: "192.168.1.1" },
  { id: "L002", action: "CREATE_INTERNSHIP",user: "hr@kcca.go.ug",        detail: "Created: Software Development Intern",     timestamp: "2026-07-27T09:15:00Z", ip: "192.168.1.5" },
  { id: "L003", action: "SHORTLIST",        user: "hr@kcca.go.ug",        detail: "Shortlisted APP001 (Sarah Nakimuli)",       timestamp: "2026-07-27T10:00:00Z", ip: "192.168.1.5" },
  { id: "L004", action: "USER_CREATED",     user: "admin@kcca.go.ug",     detail: "Created user: allan.m@kcca.go.ug",         timestamp: "2026-07-27T10:30:00Z", ip: "192.168.1.1" },
  { id: "L005", action: "REPORT_GENERATED", user: "hr@kcca.go.ug",        detail: "Generated Applications Report (PDF)",       timestamp: "2026-07-27T11:00:00Z", ip: "192.168.1.5" },
  { id: "L006", action: "LOGIN",            user: "applicant@kcca.go.ug", detail: "Applicant logged in",                      timestamp: "2026-07-27T11:30:00Z", ip: "192.168.10.2" },
  { id: "L007", action: "SUBMIT_APP",       user: "applicant@kcca.go.ug", detail: "Submitted application for Finance Intern",  timestamp: "2026-07-27T11:45:00Z", ip: "192.168.10.2" },
];
